FROM node:16

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

RUN npm install

# Bundle app source
COPY . .

ENV QUARKUS_HTTP_SSL_PORT=1345

CMD [ "node", "server.js" ]
